// Lista completa de especies/cultivos disponibles para análisis
export const CROP_SPECIES = {
  // Cultivos anuales y hortícolas
  VEGETABLES_AND_CROPS: [
    'Acelga',
    'Achicoria',
    'Ajo',
    'Ajo brandino',
    'Ajo ornamental',
    'Ajo silvestre',
    'Ají',
    'Ají ornamental',
    'Albahaca',
    'Alcachofa',
    'Alfalfa',
    'Alfalfón',
    'Almendra',
    'Alpiste',
    'Apio',
    'Arroz',
    'Arveja',
    'Arvejilla',
    'Avena',
    'Azafrán',
    'Ballica inglesa',
    'Ballica italiana',
    'Ballico',
    'Berenjena',
    'Berro',
    'Betarraga común',
    'Black gram',
    'Black gram mungo',
    'Brócoli',
    'Bunching',
    'Cacao',
    'Café',
    'Calabaza',
    'Camote',
    'Canónico',
    'Cardilla',
    'Carinata',
    'Cártamo',
    'Caña de azúcar',
    'Cebada',
    'Cebadilla',
    'Cebolla',
    'Cebolla ornamental',
    'Centeno',
    'Chalota',
    'Chayote',
    'Ciboulette',
    'Cilantro',
    'Clavel japonés',
    'Col de olor',
    'Col forrajera',
    'Coliflor',
    'Curagüilla',
    'Cáñamo',
    'Endivias',
    'Espárrago comestible',
    'Espinaca',
    'Esponja vegetal',
    'Falaris',
    'Festuca',
    'Frejol',
    'Frejol adzuki',
    'Garbanzos',
    'Gin seng',
    'Haba',
    'Haba de lima',
    'Hierba de san juan',
    'Hinojo',
    'Jengibre',
    'Kale',
    'Kiwano',
    'Kohlrabi',
    'Lavanda',
    'Lechuga',
    'Lenteja',
    'Lolium',
    'Lotera',
    'Lupino',
    'Lupulo',
    'Maní',
    'Mantra',
    'Manzanilla',
    'Marrubio',
    'Matrizcaria',
    'Maíz',
    'Meliloto',
    'Melón',
    'Menta',
    'Menta negra',
    'Mizuna',
    'Mostaza blanca',
    'Mostaza negra',
    'Musgo',
    'Nabo',
    'Name',
    'Onagra',
    'Orégano',
    'Orégano ratón',
    'Papa',
    'Pasto ovillo',
    'Pepino',
    'Pepino dulce',
    'Pimiento',
    'Pimiento morrón',
    'Poroto',
    'Puerro',
    'Quinoa',
    'Rabanito',
    'Radicha',
    'Raps',
    'Remolacha azucarera',
    'Repollo',
    'Repollo de bruselas',
    'Repollo chino',
    'Repollo crespo',
    'Rúcula',
    'Ruibarbo',
    'Rutabaga',
    'Rábano',
    'Sandía',
    'Sorgo',
    'Soya',
    'Tabaco',
    'Taro',
    'Tomate',
    'Tomatillo',
    'Topinambur',
    'Toronjil',
    'Trigo',
    'Trigo candeal',
    'Triticale',
    'Trébol',
    'Trébol alejandrino',
    'Trébol blanco',
    'Trébol encarnado',
    'Trébol ladino',
    'Trébol rosado',
    'Trébol subterráneo',
    'Té',
    'Vainilla',
    'Vicia púrpura',
    'Yuca mandioca',
    'Zanahoria',
    'Zapallito',
    'Zapallo italiano'
  ],

  // Frutales y árboles
  FRUITS_AND_TREES: [
    'Achachariu',
    'Almendro',
    'Anona',
    'Arándano',
    'Avellano',
    'Avellano autóctono',
    'Babaco',
    'Bergamota',
    'Calamondine',
    'Caqui',
    'Castaña de caju',
    'Castaño',
    'Cerezo agrio',
    'Cerezo de flor',
    'Cerezo de otoño',
    'Cerezo de japón',
    'Cerezo dulce',
    'Chirimoya',
    'Ciruelo europeo',
    'Ciruelo japonés',
    'Clementino',
    'Cranberries',
    'Cítrico',
    'Cítrico híbrido',
    'Damasco',
    'Duraznero',
    'Feijoa',
    'Frambueso',
    'Fresa',
    'Frutilla',
    'Granado',
    'Granado enano',
    'Grosella',
    'Guanábana',
    'Guayabo',
    'Guindo',
    'Higuera',
    'Kiwi amarillo',
    'Kiwi baby',
    'Kiwi rojo',
    'Kiwi verde',
    'Kumquat',
    'Lima',
    'Lima ácida',
    'Limón',
    'Limón de portugal',
    'Limón tahiti',
    'Litchi',
    'Lúcumo',
    'Macadamia',
    'Mandarino',
    'Mango',
    'Manzano',
    'Manzano común',
    'Maracuyá',
    'Membrillo',
    'Mora',
    'Murta',
    'Naranjo',
    'Naranjo agrio',
    'Naranjo dulce',
    'Naranjo trifoliado',
    'Nectarino',
    'Nogal',
    'Níspero',
    'Olivo',
    'Palma chilena',
    'Palma cocotero',
    'Palto',
    'Papaya',
    'Pecano',
    'Peral',
    'Peral asiático',
    'Physalis',
    'Pigeon pea',
    'Pistacho',
    'Piña',
    'Plátano común',
    'Pomelo',
    'Pomelo toronja',
    'Prunus',
    'Riñón',
    'Tamarindo',
    'Tangelo',
    'Tumbo',
    'Vid'
  ]
} as const

// Lista completa combinada para fácil uso
export const ALL_SPECIES = [
  'Desconocido', // Opción por defecto
  ...CROP_SPECIES.VEGETABLES_AND_CROPS.sort(),
  ...CROP_SPECIES.FRUITS_AND_TREES.sort()
].sort()

// Categorías para organización en el dropdown
export const SPECIES_CATEGORIES = [
  {
    label: 'Cultivos y Hortalizas',
    options: CROP_SPECIES.VEGETABLES_AND_CROPS.sort()
  },
  {
    label: 'Frutales y Árboles',
    options: CROP_SPECIES.FRUITS_AND_TREES.sort()
  }
] as const

// Tipo para TypeScript
export type SpeciesType = typeof ALL_SPECIES[number]